# Generated by Django 3.2.9 on 2022-01-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBodega', models.CharField(max_length=100)),
                ('direccionBodega', models.CharField(max_length=200)),
                ('telefonoBodega', models.CharField(max_length=200)),
                ('encargadoBodega', models.CharField(max_length=50)),
                ('creadoBodega', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=50)),
                ('creadoCategoria', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=150)),
                ('nombreColor', models.CharField(blank=True, max_length=20, verbose_name='Color')),
                ('nombreMedidas', models.CharField(blank=True, max_length=40)),
                ('nombreMarca', models.CharField(blank=True, max_length=20, null=True)),
                ('nombreModelo', models.CharField(blank=True, max_length=20)),
                ('nombreSerial', models.CharField(blank=True, max_length=20)),
                ('stockProducto', models.IntegerField()),
                ('precioProducto', models.IntegerField(blank=True, verbose_name='Precio Compra')),
                ('fechaCompra', models.DateField(auto_now_add=True)),
                ('creadoProducto', models.DateTimeField(auto_now_add=True)),
                ('nombreBodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlBodega.bodega')),
                ('nombreCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlBodega.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('cargoUsuario', models.CharField(max_length=20)),
                ('creadoUsuario', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockRetiro', models.IntegerField()),
                ('creadoRetiro', models.DateTimeField(auto_now_add=True)),
                ('nombreProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlBodega.producto')),
                ('nombreUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlBodega.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controlBodega.proveedor'),
        ),
    ]
